name: Check for broken links

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check links with md-dead-link-check
        uses: AlexanderDokuchaev/md-dead-link-check@v1.0
