name: Generate XML sitemap

on:
  push:
    branches: [ main ]   # 当推送到 main 分支时触发

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    # 1. 拉取你的仓库代码（需要 fetch-depth: 0 来获取完整的 Git 历史）
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. 调用生成 sitemap 的程序
    - name: Generate the sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://fortunecord.github.io/fortunecord-artworks/

    # 3. 检查并提交生成的 sitemap.xml 文件
    - name: Commit and push the sitemap
      run: |
        if [[ `git status --porcelain sitemap.xml` ]]; then
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add sitemap.xml
          git commit -m "Automated sitemap update"
          git push
        fi
